name: speakable
description: A Flutter application for speech and language assistance.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.7.2

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2

  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.5
  path_provider: ^2.1.5

  # Speech & Audio
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.3
  audioplayers: ^5.2.1

  # Image & File Handling
  image_picker: ^1.2.0
  file_picker: ^8.3.7

  # Network
  http: ^1.5.0

  # Utilities
  intl: ^0.19.0
  permission_handler: ^11.4.0
  android_intent_plus: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
    - assets/images/
    - assets/feelings-emojis/
    - assets/Food-image/
    - assets/Drinks-image/
    - assets/Travel-image/
